name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Build Fast
      run: docker build invoice/. --file Dockerfile --tag ntrphanikumar/leaze9-invoice:1.0.0 --tag ntrphanikumar/leaze9-invoice:1.0.0.$(date '+%Y%m%d')
    - name: Docker Push Warmer
      run: docker push ntrphanikumar/leaze9-invoice --all-tags
